"""Added new columns in Book, Member, and IssueRecords

Revision ID: 0a26b2028d4d
Revises: 
Create Date: 2024-03-10 06:24:54.766740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a26b2028d4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_t_stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('b_c_stock', sa.Integer(), nullable=False))
        batch_op.alter_column('b_authors',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('b_lang',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('b_isbn',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('b_stock')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('m_books_issued', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
        batch_op.add_column(sa.Column('m_due_fees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('m_total_fees', sa.Float(), nullable=True))
        batch_op.drop_column('m_books')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('m_books', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('m_total_fees')
        batch_op.drop_column('m_due_fees')
        batch_op.drop_column('m_books_issued')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_stock', sa.INTEGER(), nullable=True))
        batch_op.alter_column('b_isbn',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('b_lang',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('b_authors',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('b_c_stock')
        batch_op.drop_column('b_t_stock')

    # ### end Alembic commands ###
